[envs.default]
dependencies = [
  "freezegun==1.2.*",
  "pytest-cov==4.1.*",
  "pytest==7.3.*",
]

[envs.default.scripts]
cov-test = "pytest --cov=schwifty tests {args:schwifty}"
test = "cov-test --no-cov"

[envs.lint]
extra-dependencies = [
  "ruff==0.0.290",
  "black==23.9.*",
  "mypy==1.5.*",
  "doc8==1.1.*",
  "pygments==2.16.*",
]

[envs.lint.scripts]
typing = "mypy --install-types --non-interactive {args:schwifty tests}"
style = [
  "black --check --diff {args:.}",
  "ruff {args:.}",
]
fmt = [
  "black {args:.}",
  "ruff --fix {args:.}",
]
docs = "doc8 docs/source"

